# Site settings
title: Arduino Day | Arduino-SC
description: "Arduino Day hotsite"
baseurl: "/arduino-day" # the subpath of your site, e.g. /blog
url: "" # the name of your domain
logo_url: img/arduino-logo-text.png

# Hero
hero: 
    hero_img: arduinos/arduino-4.jpeg
    hero_title: Arduino Day
    hero_description: Um evento para os admiradores e usuários de Arduino e relacionados.

# Contact form
api_token: f56bb59f975426ceca9e08636eaab5c4

# Contact info
contact:
    # phone: 932 50 540
    # emergency: 931 53 234
    email: mrprompt+arduino-sc@gmail.com
    address: Florianópolis, <br> Santa Catarina - Brasil

# Testimonials
testimonials:
    testimonials_img: parallax.jpg

# Map
map:
    zoom: 30
    address: Centro - Florianóplis, SC, Brazil
    address_details: svg/min/logo.svg

# Social settings
# facebook: http://facebook.com
twitter: http://twitter.com/arduino_sc
# instagram: http://instagram.com
# youtube: http://youtube.com
# skype: skype:obaez_design?userinfo
whatsapp: https://chat.whatsapp.com/Fg4DEDyPbGW121eUuE5Pan
feed: yes

# Footer
copyright: 2018 Arduino-SC

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics: UA-116538996-1
google_verification: AIzaSyByw7AqzbYASj16OB1LbBilo7vZtunHP0I
